/* Pricing comparison data for Growth Consultation page. */
export const PACKAGES = [
  {
    slug: 'pilot',
    name: 'Quick-Start Pilot',
    goal: 'Risk-free 15-day execution proof',
    market: '₹15,000–₹25,000+',
    ours: '₹4,999',
    duration: '15 Days',
    best: 'SHGs, Local Businesses, First-Time Digital Users',
    why: 'Removes risk while proving execution capability.',
    note: '+12.5% charges for contract-based secured agreement',
    items: [
      { label: 'Business & Digital Snapshot Audit', price: '₹1,500' },
      { label: 'Platform Optimization + Content (1 Platform)', price: '₹1,500' },
      { label: 'Basic Lead Entry Setup', price: '₹1,000' },
      { label: 'Reach Boost / Promo Test', price: '₹500' },
      { label: 'Performance Review + Scale Plan', price: '₹500' },
    ],
  },
  {
    slug: 'starter',
    name: 'Starter Package',
    goal: 'Visibility, basic trust, digital presence',
    market: '₹25,000–₹45,000+/mo',
    ours: '₹15,000–₹35,000/mo',
    best: 'SHGs, Local Businesses, First-Time Digital Users',
    why: 'Low risk, easy entry, builds digital discipline.',
    items: [
      { label: 'Social Media Setup & Management', price: '₹4,000–₹10,000+', market: '₹6,000–₹12,000+' },
      { label: 'Content Strategy & Posting', price: '₹4,000–₹10,000+', market: '₹8,000–₹12,000+' },
      { label: 'Basic Lead Setup (WhatsApp/Forms)', price: '₹2,500–₹5,000', market: '₹4,000–₹7,000+' },
      { label: 'Digital Audit & Guidance', price: '₹2,500–₹6,000', market: '₹4,000–₹8,000+' },
      { label: 'Monthly Performance Report', price: '₹2,000–₹4,000', market: '₹3,000–₹6,000+' },
    ],
  },
  {
    slug: 'growth',
    name: 'Growth Package',
    goal: 'Consistent leads, systems, conversion clarity',
    market: '₹60,000–₹1,00,000+/mo',
    ours: '₹45,000–₹80,000+/mo',
    best: 'Businesses aiming for traction & leads, Mid-scale Startups',
    why: 'Introduces systems instead of guesswork.',
    items: [
      { label: 'Social Media & Content Execution', price: '₹15,000–₹25,000+', market: '₹20,000–₹30,000+' },
      { label: 'Paid Ads Management (Meta/Google)', price: '₹8,000–₹15,000+', market: '₹10,000–₹20,000+', sub: 'Ad spend excluded' },
      { label: 'Lead Funnel Setup', price: '₹8,000–₹15,000+', market: '₹10,000–₹13,000+' },
      { label: 'WhatsApp Automation & Follow-ups', price: '₹8,000–₹15,000+', market: '₹12,000–₹25,000+' },
      { label: 'Monthly Strategy Review & Reporting', price: '₹6,000–₹10,000+', market: '₹8,000–₹12,000+' },
    ],
  },
  {
    slug: 'scale',
    name: 'Scale Package',
    goal: 'Aggressive growth, automation, revenue alignment',
    market: '₹1,50,000–₹3,00,000+/mo',
    ours: '₹1,20,000–₹2,00,000+/mo',
    best: 'Fast-Growing Businesses & Multi-Venture Owners',
    why: 'Positions Flareonix as a long-term growth partner.',
    items: [
      { label: 'Full-Funnel Marketing Strategy', price: '₹35,000–₹60,000+', market: '₹45,000–₹80,000+' },
      { label: 'Performance Marketing', price: '₹35,000–₹50,000+', market: '₹40,000–₹70,000+' },
      { label: 'CRM + Advanced Automation', price: '₹20,000–₹35,000+', market: '₹25,000–₹60,000+' },
      { label: 'Retargeting & Conversion Optimisation', price: '₹20,000–₹35,000+', market: '₹25,000–₹50,000+' },
      { label: 'Business Growth Consulting & Reviews', price: '₹10,000–₹20,000+', market: '₹15,000–₹40,000+' },
    ],
  },
];

export const OTHER_SERVICES = [
  { name: 'Pitch Preparation & Investor Readiness', why: 'Investor-ready clarity from a startup-native partner.' },
  { name: 'Brand Building & Digital Presence', why: 'Premium identity for ambitious founders.' },
  { name: 'Lead Generation & Funnel Building', why: 'Predictable pipeline, not random reach.' },
  { name: 'WhatsApp / CRM Automation', why: 'Convert chats into customers, hands-free.' },
  { name: 'Business Development Support', why: 'Open doors and close partnerships faster.' },
  { name: 'Website Development & Management', why: 'High-converting sites that ship in days.' },
  { name: 'App Development (No-Code / MVP)', why: 'Validate ideas before investing in code.' },
  { name: 'E-Commerce Store Setup', why: 'Sell online with a full storefront in 2 weeks.' },
  { name: 'Logo, Branding & Content Creation', why: 'Visuals that match the firepower of your story.' },
  { name: 'Growth Consulting (sessions or ongoing)', why: 'A founder-coach in your corner.' },
  { name: 'Event & Sponsorship Activation', why: 'Turn events into ecosystem leverage.' },
  { name: 'Reputation & PR Management', why: 'Own the narrative before others write it.' },
  { name: 'Strategy Workshops (in-person / online)', why: 'Get 90 days of clarity in one session.' },
  { name: 'Founder Personal Branding', why: 'You are the product — let it show.' },
  { name: 'Any required service — modular & customizable', why: 'If it helps you grow, we build it.' },
];

export const ENGAGEMENT_OPTIONS = [
  { title: 'Risk-Free Growth Credit', desc: '100% refund if first 30-day milestone is not hit. Total skin in the game.' },
  { title: "Founder's Early-Partner Advantage", desc: 'Locked-in legacy rates for the first 12 months when you onboard early.' },
  { title: 'Performance Booster Add-On', desc: 'Pay a flat retainer + a small upside fee — we eat what we kill.' },
  { title: 'Multi-Business & Referral Deal', desc: 'Bring two ventures (yours or referred) and unlock a permanent discount.' },
];
